# Generated by Django 4.2.7 on 2024-09-24 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField(auto_now=True)),
                ('preco_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CompraProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_produtos.compra')),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_produtos.produto')),
            ],
        ),
    ]
