# Generated by Django 4.2.7 on 2024-09-29 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_produtos', '0003_remove_compra_preco_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'permissions': (('add_produtos', 'Pode adicionar produtos'),)},
        ),
    ]
