# Generated by Django 4.2.7 on 2024-09-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_produtos', '0004_alter_produto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraproduto',
            name='quantidade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
