# Generated by Django 4.2.7 on 2024-09-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_produtos', '0005_compraproduto_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraproduto',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
